config/routes.rb
  delete '/basket/destroy/:id',             to: 'basket#destroy',                          as: :basket_destroy

  post   '/basket/update/:id',              to: 'basket#update',                           as: :basket_update
  patch  '/basket/share/:id',               to: 'basket#share',                            as: :basket_share
  patch  '/basket/clone/:id',               to: 'basket#clone',                            as: :basket_clone
  post   '/basket/banner/:id',              to: 'basket#banner_upload',                    as: :basket_banner
  post   '/basket/default_banner/:id',      to: 'basket#banner_default',                   as: :lifestyle_default_banner

  # Event
  get    '/:username/event/:id',            to: 'events#view',                             as: :event_view
  post   '/event/remove/:id',               to: 'events#remove',                           as: :event_remove
  post   '/event/update/:id',               to: 'events#update',                           as: :event_update
  post   '/event/banner/:id',               to: 'events#banner_upload',                    as: :event_banner
  post   '/event/default_banner/:id',       to: 'events#banner_default',                   as: :event_default_banner
  patch  '/event/confirm',                  to: 'events#confirm_invitation',               as: :event_confirm_invitation
  patch  '/event/maybe',                    to: 'events#maybe_invitation',                 as: :event_maybe_invitation
  patch  '/event/reject',                   to: 'events#reject_invitation',                as: :event_reject_invitation
  patch  '/event/invite_customer/:id',      to: 'events#invite_customer',                  as: :event_invite_customer
  # Charity
  get    '/:username/charity/:id',           to: 'charity#view',                           as: :charity_view
  post   '/charity/update/:id',             to: 'charity#update',                          as: :charity_update
  post   '/charity/banner/:id',             to: 'charity#banner_upload',                   as: :charity_banner
  post   '/charity/default_banner/:id',     to: 'charity#banner_default',                  as: :charity_default_banner

  # Cash
  get    '/cash',                           to: 'cash#view',                               as: :cash_view

  delete '/oauth/disconnect',               to: 'customers/omniauth#destroy',              as: :oauth_disconnect

  #welcome page
  get    '/welcome',                        to: 'site#welcome',                            as: :welcome

  #sitemap page
  get    '/sitemaps',                       to: 'site#sitemaps',                           as: :sitemaps

  # Feed
  get    '/feed/following',                 to: 'feed#following',                          as: :following_feed
  get    '/feed/products',                  to: 'feed#products',                           as: :products_feed
  get    '/feed/most-active',               to: 'feed#most_active',                        as: :most_active_feed

  #search
  get    '/search',                         to: 'feed#search',                             as: :search
  get    '/friend-search',                  to: 'feed#friend_search',                      as: :friend_search
  get    '/search-for-friends',             to: 'site#customers_search',                   as: :search_customers

  post   '/browsing',                       to: 'site#browsing'

  #Discover
  get    '/discover/brands',                to: 'discover#discover_brands',                as: :discover_brands
  get    '/discover/deals',                 to: 'discover#discover_deals',                 as: :discover_deals
  get    '/discover/categories',            to: 'discover#discover_categories',            as: :discover_categories
  get    '/discover/wish-lists',            to: 'discover#discover_wish_lists',            as: :discover_wish_lists
  get    '/discover/categories/:category',  to: 'discover#discover_search_categories',     as: :discover_search_categories
  get    '/sort/discover',                  to: 'discover#sort',                           as: :discover_sort
  get    '/paginate/discover',              to: 'discover#paginate',                       as: :discover_paginate

  # Modal Builders
  get    '/products/modal_builder/:id',     to: 'products#modal_builder',                  as: :products_modal_builder
  get    '/products/modal_leave/:id',       to: 'products#modal_leave',                    as: :products_modal_leave
  get    '/basket/modal_builder/:id',       to: 'basket#modal_builder',                    as: :basket_modal_builder
  patch  '/basket/modal_destroy/:id',       to: 'basket#modal_destroy',                    as: :basket_modal_destroy
  patch  '/profile/modal_share/:id',        to: 'customers/profile#modal_share',           as: :customer_modal_share

  # Popup Builders
  patch  '/basket/popup_share/:id',         to: 'basket#popup_share',                      as: :basket_popup_share

  # Product
  get    '/products',                       to: 'products#index',                          as: :products_index
  get    '/products/:id',                   to: 'products#show',                           as: :variant
  patch  '/products/add-tags',              to: 'products#add_tags',                       as: :products_add_tag

  #BASKET INFINITE SCROLL PAGINATION
  get    '/paginate/basket',                to: 'basket#paginate_basket',                  as: :basket_paginate

  resource :checkout, only: [:create, :show] do
    collection do
      get  'guest_email'
      get  'confirm'
      get  'amazon_prime'
      get  'order_placed'
    end
  end

  # Gift
  get    '/gift/:id',                       to: 'gift#view',                               as: :gift_view
  patch  '/gift/rate',                      to: 'gift#rate',                               as: :gift_rate
  delete '/gift/destroy',                   to: 'gift#destroy',                            as: :gift_destroy
  patch  '/gift/share/:id',                 to: 'gift#share',                              as: :gift_share
  patch  '/gift/quantity_change/:id',       to: 'gift#quantity_change',                    as: :gift_quantity_change
  patch  '/gift/add-tags',                  to: 'gift#add_tags',                           as: :gift_add_tag
  patch  '/gift/confirm',                   to: 'gift#confirm',                            as: :gift_confirm
  patch  '/gift/recieved/:id',              to: 'gift#recieved',                           as: :gift_recieved
  post   '/gift/caption/:id',               to: 'gift#caption',                            as: :gift_add_caption

  get    '/join-our-team',                  to: 'site#join_our_team',                      as: :join_our_team
  get    '/faq',                            to: 'site#faq',                                as: :faq
  get    '/privacy-policy',                 to: 'site#privacy_policy',                     as: :privacy_policy
  get    '/terms-and-conditions',           to: 'site#terms',                              as: :terms
  get    '/community',                      to: 'site#community',                          as: :community
  get    '/unlimited-gifts',                to: 'site#unlimited_gifts',                    as: :unlimited_gifts
  get    '/feedback',                       to: 'site#feedback',                           as: :feedback
  post   '/complaint',                      to: 'site#complaint',                          as: :new_complaint

  patch  '/notifications/mark-as-read',     to: 'notifications#mark_as_read',              as: :notifications_mark_as_read

  #NOTIFICATIONS INFINITE SCROLL PAGINATION
  get    '/paginate/notifications',         to: 'customers/profile#paginate_notifications',as: :notifications_paginate

  patch  '/comments/create',                to: 'comments#create',                         as: :comments_create
  patch  '/comments/delete/:id',            to: 'comments#delete',                         as: :comments_delete

  patch  '/activities/share',               to: 'activities#share',                        as: :activities_share

  patch  '/likes/toggle',                   to: 'likes#toggle',                            as: :likes_toggle

  delete '/customer/deactivate',            to: 'customers/views#deactivate',              as: :customer_deactivate
  patch  '/customer/share/:id',             to: 'customers/views#share',                   as: :customer_share
  post   '/customer/category',              to: 'customers/views#category',                as: :customer_category

  #FACEBOOK POPUP CONNECTION
  post   '/customer/fb-popup-session',      to: 'customers/views#fb_popup_session',        as: :customer_fbpopup_session
  post   '/customer/fb-popup-db',           to: 'customers/views#fb_popup_db',             as: :customer_fbpopup_db
  post   '/customer/fromfb',                to: 'customers/views#fromfb',                  as: :customer_fromfb

  #CUSTOMER INFINITE SCROLL PAGINATION
  get    '/paginate/wishlist',              to: 'customers/views#wishlist',                as: :paginate_wishlist
  get    '/paginate/connection',            to: 'customers/views#connection',              as: :paginate_connection
  get    '/paginate/wishes',                to: 'customers/views#wishes',                  as: :paginate_wishes

  post   '/profile/avatar',                 to: 'customers/profile#avatar_upload',         as: :customer_avatar
  post   '/profile/banner',                 to: 'customers/profile#banner_upload',         as: :customer_banner
  post   '/profile/default_banner',         to: 'customers/profile#banner_default',        as: :customer_default_banner
  post   '/profile/default_avatar',         to: 'customers/profile#avatar_default',        as: :customer_default_avatar

  patch  '/profile/update',                 to: 'customers/profile#profile_update',        as: :profile_update
  patch  '/profile/basic-update',           to: 'customers/profile#basic_update',          as: :basic_update

app/controllers/discover_controller.rb
class DiscoverController < ApplicationController

  before_action :available_deals

  def discover_categories
    c = categories.sort!{ | x, y | x[:name].downcase <=> y[:name].downcase }.uniq
    @categories = c.paginate(page: 1, per_page: 30) 
    @title = "Discover Categories"
    @meta_description = 'Building a gift registry? These companies have products that can be easily added to your wish lists in a few simple clicks.'
  end

  def discover_wish_lists
    b = wish_lists
    @baskets = b.paginate(page: 1, per_page: 30) 
    @title = "Discover Wish Lists"
    @meta_description = 'Take a look at some of our member\'s personal registries to get ideas for how you can set up your very own wish list on Giftibly.'
  end

  def discover_search_categories
    b = search_categories
    @brands = b.paginate(page: 1, per_page: 30) 
    @title = "#{params[:category].titleize} Category"
    @meta_description = "Discover #{params[:category].titleize} items. Add them to your personal registry, share them with friends, only on Giftibly."
    @category = MerchantCategory.friendly.find params[:category]
  end

  def discover_deals
    d = deals
    @deals = d.paginate(page: 1, per_page: 30) 
    @title = "Discover Deals"
    @meta_description = 'Occasionally we will post coupon offers for great savings on wonderful gifts. You can find them here!'
  end

#  def discover_brands
#    @title = "Discover Brands"
#    brands = Merchant.where.not( screenshot: nil).order( created_at: 'desc' )
#
#    if params[:q].present?
#      @brands = @brands.paginate(page: params[:page], per_page: 30) 
#    else
#      @brands = brands.paginate(page: params[:page], per_page: 30) 
#    end 
#  end

  def sort
    sort_then_paginate
  end

  def paginate
    sort_then_paginate
  end

  private

  def available_deals
    if !Deal.active_small.empty? || !Deal.active_large.empty?
      @deals = true
    end
  end

  def wish_lists
      baskets = Basket.where( privacy: "public", basket_type: "lifestyle" ).collect { |b| b if b.gifts.count > 7 }.compact
      return baskets 
  end

  def categories
    MerchantCategory.all.collect{|t| t}.flatten.uniq
  end

  def search_categories
    c = ActsAsTaggableOn::Tag.where( permalink: params[:category] ).first
    return c.present? ? ActsAsTaggableOn::Tagging.where( context: "categories", tag_id: c.id ).collect { |t| t.taggable }.flatten : []
  end

  def deals
      deals = []

      small_deals = Deal.active_small if !Deal.active_small.empty?
      large_deals = Deal.active_large if !Deal.active_large.empty?

      if small_deals.present?
         small_deals.each do |s|
          deals << s
         end
      end

      if large_deals.present?
         large_deals.each do |l|
          deals << l
         end
      end

      return deals
  end


  def char(discover_type, char)
    
    discover_sort = []
    
    if discover_type == 'wish_lists'

      b = wish_lists
      b.each do |basket|
        if basket.name.downcase.include?(char.downcase)
          discover_sort << basket
        end  
      end 

    elsif discover_type == 'categories'

      c = categories
      c.each do |category|
        if category[:name].downcase.include?(char.downcase)
          discover_sort << category
        end  
      end 

    elsif discover_type == 'brands' || discover_type == 'category_search'

      b = search_categories
      b.each do |brand|
        if brand.name.downcase.include?(char.downcase)
          discover_sort << brand
        end  
      end 
      
    elsif discover_type == 'deals'

      d = deals
      d.each do |deal|
        if deal.name.downcase.include?(char.downcase)
          discover_sort << deal
        end  
      end 

    end

    return discover_sort

  end

  def sort_then_paginate
    
    #WISHLISTS
    if params[:discover_type] == 'wish_lists'
      
      if params[:sort] == 'a-z'
        b = wish_lists.sort!{ | x, y | x.name.downcase <=> y.name.downcase }.uniq
      elsif params[:sort] == 'z-a'
        b = wish_lists.sort!{ | x, y | y.name.downcase <=> x.name.downcase }.uniq
      elsif params[:char].present?
        b = char( params[:discover_type], params[:char] )
      else
        b = wish_lists.shuffle
      end

      @baskets = b.paginate(page: params[:page], per_page: 30)

    #CATEGORIES
    elsif params[:discover_type] == 'categories'

      if params[:sort] == 'a-z' #A - Z
        c = categories.sort!{ | x, y | x[:name].downcase <=> y[:name].downcase }.uniq
      elsif params[:sort] == 'z-a' #Z - A
        c = categories.sort!{ | x, y | y[:name].downcase <=> x[:name].downcase }.uniq
      elsif params[:char].present?
        c = char( params[:discover_type], params[:char] )
      else #Random
        c = categories.shuffle
      end

      @categories = c.paginate(page: params[:page], per_page: 30) 
          
    #DEALS
    elsif params[:discover_type] == 'brands' || params[:discover_type] == 'category_search'

      @category = params[:category]

      if params[:sort] == 'a-z' #A - Z
        b = search_categories.sort!{ | x, y | x.name.downcase <=> y.name.downcase }.uniq
      elsif params[:sort] == 'z-a' #Z - A
        b = search_categories.sort!{ | x, y | y.name.downcase <=> x.name.downcase }.uniq
      elsif params[:char].present?
        b = char( params[:discover_type] , params[:char])
      else #Random
        b = search_categories.shuffle
      end

      @brands = b.paginate(page: params[:page], per_page: 30) 
    
    #DEALS
    elsif params[:discover_type] == 'deals'

      if params[:sort] == 'a-z' #A - Z
        d = deals.sort!{ | x, y | x.name.downcase <=> y.name.downcase }.uniq
      elsif params[:sort] == 'z-a' #Z - A
        d = deals.sort!{ | x, y | y.name.downcase <=> x.name.downcase }.uniq
      elsif params[:char].present?
        d = char( params[:discover_type], params[:char])
      else #Random
        d = deals.shuffle
      end

      @deals = d.paginate(page: params[:page], per_page: 30)

    end

    respond_to do |format|
      format.js 
    end

  end
        
end

app/views/shared/discover/_discover_body.html.erb
<div id="discover_body" class="<%= discover_type == 'category_search' ? 'discover_search' : 'discover' %>">
    <%= render partial: "shared/discover/discover_nav", locals: {discover_type: discover_type} %>

    <div id="discover_feed">
        <% if (discover_type == 'brands' || discover_type == 'category_search' && @brands.present?) %>    
            <% @brands.each do |brand| %>
                <%= render partial: "shared/tiles/discover_tiles/brand_tiles", locals: {brand: brand} %>
            <% end %>
        <% elsif discover_type == 'categories' && @categories.present? %>
            <% @categories.each do |category| %>
                <%= render partial: "shared/tiles/discover_tiles/category_tiles", locals: {category: category} %>
            <% end %>
        <% elsif discover_type == 'wish_lists' && @baskets.present? %>
            <% @baskets.reverse.shuffle.each_slice(2) do |a, b| %>
              <div class="grouped_lists">
                  <%= render partial: "shared/tiles/basket_tile", locals: {basket: a, basket_type: 'discover'} if a.present? %>
                  <%= render partial: "shared/tiles/basket_tile", locals: {basket: b, basket_type: 'discover'} if b.present? %>
              </div>
            <% end %>
        <% elsif discover_type == 'deals' && @deals.present? %>
          <div class="deals_container">
            <% @deals.each do |deal| %>
              <%= render partial: "shared/tiles/discover_tiles/deals_tile", locals: {deal: deal} %>
            <% end %>
          </div>
        <% end %>
    </div>

    <div id="loader" class="discover">
        <i aria_hidden="true" class="icon ion-load-c spinner icon_center"></i>
    </div>
    
</div>


<script rel="nofollow" type="text/javascript">
    function lazy(){
        $('.lazy').Lazy({
            effect: "fadeIn",
            effectTime: 800,
            threshold: 0,
            delay: 0
        });
    }
    
    var sort = "<%=discover_type == 'categories'? '&sort=a-z' : '&sort=random' %>";
    var page_discover = 1;

    var page_type = "/paginate/discover?discover_type=<%=discover_type %>&page="
    $('.group_tile, .brand').addClass('fade-animate');

    $('.sort_nav a').click(function(){
      sort = '&sort='+$(this).attr('href').split('&sort=')[1];
      page_discover = 1;
      setTimeout(function(){
          lazy();
      }, 1000)
    });

    <% if discover_type == 'category_search' %>
       sort = sort+="&category=<%=@category.name%>";
       $('.sort_nav a').each(function(e){
        new_url = $(this).attr('href')+"&category=<%=@category.name%>"
        $(this).attr('href', new_url)
       })
    <% end %>
    
    $("input[name='discover_search_<%=discover_type %>']").on('keyup touchend', function(e){
      if (this.value.length >= 1) {
        
        <% if discover_type == 'category_search' %>
        sort_url = "/sort/discover?discover_type=<%=discover_type %>&char="+ this.value + "&category=<%=@category.name%>";
        <% else %>
        sort_url = "/sort/discover?discover_type=<%=discover_type %>&char="+ this.value;
        <% end %>

      }else{
        page_discover = 1;

        <% if discover_type == 'category_search' %>
        sort_url = "/sort/discover?discover_type=<%=discover_type %>&category=<%=@category.name%>&page=1&sort=" + sort;
        <% else %>
        sort_url = "/sort/discover?discover_type=<%=discover_type %>&page=1&=" + sort;
        <% end %>

      }
        $.ajax({
          type     : 'GET',
          url      : sort_url,
          dataType : 'script',
          encode   : true,
          success  : function(){
              lazy();
          }
        });
    });

    var controller = new ScrollMagic.Controller();

    <% if browser.mobile? %>
        var offset_height = -3000;
    <% else %>
        var offset_height = -900;
    <% end %>

  // build scene
    var scene = new ScrollMagic.Scene({triggerElement: "#loader", offset: offset_height})
    .addTo(controller)
    .on("enter", function (e) {
        if (e.scrollDirection == "FORWARD") {
            page_discover++;
            $("#loader i").addClass("active");
            var  discover_url = page_type + page_discover + sort ;
            $.ajax({
                url: discover_url, //pagination url
                type: 'GET',
                success: function (data) {
                    lazy();
                    $("#loader i").removeClass("active");
                    $('.group_tile').addClass('fade-animate');
                    var count = (data.match(/col-xs-6/g) || []).length;
                    if (count < 30 && !$('.no_more_items')[0] ){
                      $('#discover_feed').after('<p class="no_more_items discover">No more items to show.</p>');
                      $('.no_more_items').fadeIn();
                    }
                },
                error: function(){
                  console.log("Error");
                  $("#loader i").removeClass("active");

                }
            });
        }
    });
    <% if discover_type != 'category_search' %>
        var controller2 = new ScrollMagic.Controller({globalSceneOptions: {triggerHook: "onLeave"}});

        // build scene
        <% if browser.mobile? %>
            var offsetting = -165;
            var margin = -65;
        <% else %>
            var margin = -50;
            var offsetting = -180;
        <% end %>
        var scene2 = new ScrollMagic.Scene({triggerElement: "#discover_body", offset: offsetting})
                    .setClassToggle('.feed_heading', 'shadow')
                    .addTo(controller2);

        var tween = TweenMax.to(".feed_heading", .05, {'margin-top':margin});
        var scene3 = new ScrollMagic.Scene({triggerElement: "#discover_body", offset: offsetting})
                    .setTween(tween)
                    .addTo(controller2);
    <% else %>
        var controller2 = new ScrollMagic.Controller({globalSceneOptions: {triggerHook: "onLeave", duration: "100%"}});
        new ScrollMagic.Scene()
            .setTween(".discover_banner", {y: "300", ease: Linear.easeNone})
            .addTo(controller2);
        new ScrollMagic.Scene()
            .setTween(".discover_heading_text", {y: "300", ease: Linear.easeNone})
            .addTo(controller2);
    <% end %>
</script>

app/views/shared/discover/_discover_nav.html.erb
<div class="feed_heading">
    <div class="discover_heading_text">
        <% if discover_type == 'category_search' %>
            <%= link_to ion_icon('chevron-left') + 'Back To Categories', discover_categories_path, class: 'discover_back' %>
        <% end %>
        <h1>
            <span>Discover</span>
            <% if discover_type == 'category_search' %>
                <%= @category.name.titleize %>
            <% else %>
                Your Next Wish
            <% end %>
        </h1>
    </div>
    <% if discover_type != 'category_search' %>
        <ul class="feed_nav">
            <li class="<%= 'active' if discover_type == 'categories' || discover_type == 'category_search' %>">
                <%= link_to discover_categories_path, class: ('active' if discover_type == 'categories' || discover_type == 'category_search') do %>
                    <span>#Categories</span>
                <% end %>
            </li>
            <li class="<%= 'active' if discover_type == 'wish_lists' %>">
                <%= link_to discover_wish_lists_path do %>
                    <span>#Wish Lists</span>
                <% end %>
            </li>
            <% if @deals.present? %>
                <li class="<%= 'active' if discover_type == 'deals' %>">
                    <%= link_to discover_deals_path, class: ('active' if discover_type == 'deals') do %>
                        <span>#Deals</span>
                    <% end %>
                </li>
            <% end %>
        </ul>
    <% else %>
        <div class="discover_banner">
            <%= image_tag @category.screenshot.large.url %>
        </div>
        <!-- <img src="http://via.placeholder.com/1600x350" class="discover_banner"> -->
    <% end %>
</div>
<% if discover_type != 'deals' %>
    <div class="sort_nav">
        <ul class="list-inline text-center">

        <li class="list-inline-item search">
            <%= text_field_tag "discover_search_#{discover_type}", nil, class: 'form-control input-md', placeholder: "Search #{discover_type.titleize}"%>
        </li>

        <li class="list-inline-item">
            <%= link_to 'Sort A-Z', discover_sort_path(page: 1, sort: 'a-z', discover_type: discover_type), remote: true, method: 'get' %>
        </li>
        <li class="list-inline-item">
            <%= link_to 'Sort Z-A', discover_sort_path(page: 1, sort: 'z-a', discover_type: discover_type), remote: true, method: 'get' %> 
        </li>
        <li class="list-inline-item">
            <%= link_to 'Randomize', discover_sort_path(page: 1, sort: 'random', discover_type: discover_type), remote: true, method: 'get' %> 
        </li>

        </ul>
    </div>
<% end %>