config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }, skip: [ :sessions, :registration, :password ]
  mount ActionCable.server => '/cable'

  scope '/api' do
    scope '/v1' do
      scope '/baskets' do
        get   '/'        => 'api_baskets#index'
        get   '/create'  => 'api_baskets#create'
      end
      scope '/merchants' do
        get  '/'         => 'api_merchants#check'
      end
      scope '/products' do
        get  '/'         => 'api_products#show'
      end
      scope  '/gifts' do
        post '/add-tags' => 'api_gifts#add_tags'
      end
      scope  '/errors' do
        post '/'         => 'api_errors#submit'
      end

    end
  end

  #======== Cart feature ==========
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:none] do
        collection do
          get 'items'
          get 'items_count'
        end
      end
      resources :api_reports, only: [:create] do
        collection do
          post 'confirm'
        end
      end
      resources :cart_items, only: [:index, :create, :update, :destroy]
      resources :payment_methods, only: [:new, :create]
      resources :checkouts, only: [:create] do
        collection do
          post 'select_shipping_option'
          post 'select_shipping_address'
          post 'select_payment_method'
          get  'review'
        end
      end
      resources :addresses
      resource :gift_urls, only: [:create] do
        get :show, on: :member
        get :baskets, on: :member
        post :html, on: :member
      end
      resources :baskets, only: [:create]
    end
  end

  namespace :ajax_partials do
    resources :shipping_addresses_form, only: [:index, :new]
    resources :payment_methods_form, only: [:index, :new]
    resources :checkouts, only: [] do
      collection do
        get 'sidebar'
        get 'empty_cart'
        get 'cart_tab'
        get 'review_shipping_option'
        get 'review_payment_method'
        get 'review_shipping_address'
      end
    end
    resource :giftboxes, only: [:none] do
      collection do
        get 'giftboxes_modal'
      end
    end
  end

  #admins
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  authenticated :admin do
    namespace :admin do
      resources :app_settings, only: [:index, :edit, :update]
      resources :purchasers do
        member do
          post 'reset_password'
        end
      end
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      resource :ga_reporting, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :brand_manager, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :deals, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :merchant_categories, only: [:none] do
        collection do
          get 'home'
          get 'categories'
          get 'category'
          get 'new'
          post 'add'
          post 'edit'
          delete 'delete'
        end
      end
      resource :feedback, only: [:none] do
        collection do
          get 'home'
          get 'complaints'
          get 'purchases'
          get 'mailinglist'
        end
      end
      root 'dashboards#home', as: :root
    end
  end

  #error status route
  match    ':status',                       to: 'errors#show',                             constraints: {status: /\d{3}/}, via: :all

  get      'admin/brands/view/:id',         to: 'admin/brand_managers#view',               as: :view_admin_brand_manager
  patch    'admin/brands/edit/:id',         to: 'admin/brand_managers#edit',               as: :edit_admin_brand_manager

  get      'admin/deals/view/:id',          to: 'admin/deals#view',                        as: :view_admin_deals
  patch    'admin/deals/edit/:id',          to: 'admin/deals#edit',                        as: :edit_admin_deals
  get      'admin/deals/new',               to: 'admin/deals#new',                         as: :new_admin_deals
  post     'admin/deals/create',            to: 'admin/deals#create',                      as: :create_admin_deals

  resources :guests, only: [:update]

  #=====================

  patch '/admin/ga_reporting/resolve',      to: 'admin#ga_reports_resolve',                as: :resolve_ga_reports
  patch '/admin/complaints/resolve',        to: 'admin#complaints_resolve',                as: :complaints_reports

  #admins
  devise_for :purchaser, controllers: {
    sessions: "purchasers/sessions"
  }
  authenticated :purchaser do
    namespace :purchasers do
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      root 'shipping_orders#index', as: :root
    end
  end


  get :token, controller: 'application'

  as :customer do
    # Custom Devise routes for Registration
    get    'register',                      to: 'customers/registrations#new',             as: :new_customer_registration
    post   'register',                      to: 'customers/registrations#create',          as: :customer_registration
    get    'cancel',                        to: 'devise/registrations#cancel',             as: :cancel_customer_registration
    get    'edit',                          to: 'devise/registrations#edit',               as: :edit_customer_registration
    patch  'update',                        to: 'devise/registration#update'
    put    'update',                        to: 'devise/registrations#update'
    delete 'destroy',                       to: 'devise/registrations#destroy'

    # Custom Devise routes for Session
    get    'login',                         to: 'custom_sessions#new',                     as: :new_customer_session
    post   'login',                         to: 'custom_sessions#create',                  as: :customer_session
    delete 'logout',                        to: 'custom_sessions#destroy',                 as: :destroy_customer_session

    # Custom Devise routes for Password
    get    'password/',                     to: 'customers/passwords#new',                    as: :new_customer_password
    post   'password/',                     to: 'customers/passwords#create',                 as: :create_customer_password
    get    'password/edit',                 to: 'customers/passwords#edit',                   as: :edit_customer_password
    post   'password/update',               to: 'customers/passwords#update',                 as: :update_customer_password
    # patch  'password',                      to: 'devise/passwords#update'
    # put    'password',                      to: 'devise/passwords#update'
  end

  resources :media_contents, only: [:create]

  resources :conversations do
    resources :messages do
      collection do
        post :read
      end
    end
  end
  get '/messages/not_read'

  # Baskets
  get    '/:username/registry/:id',         to: 'basket#view',                             as: :basket_view
  post   '/basket/add/:id',                 to: 'basket#add',                              as: :basket_add
  delete '/basket/remove/:id',              to: 'basket#remove',                           as: :basket_remove
  post   '/basket/create',                  to: 'basket#create',                           as: :basket_create
  delete '/basket/destroy/:id',             to: 'basket#destroy',                          as: :basket_destroy

  post   '/basket/update/:id',              to: 'basket#update',                           as: :basket_update
  patch  '/basket/share/:id',               to: 'basket#share',                            as: :basket_share
  patch  '/basket/clone/:id',               to: 'basket#clone',                            as: :basket_clone
  post   '/basket/banner/:id',              to: 'basket#banner_upload',                    as: :basket_banner
  post   '/basket/default_banner/:id',      to: 'basket#banner_default',                   as: :lifestyle_default_banner

  # Event
  get    '/:username/event/:id',            to: 'events#view',                             as: :event_view
  post   '/event/remove/:id',               to: 'events#remove',                           as: :event_remove
  post   '/event/update/:id',               to: 'events#update',                           as: :event_update
  post   '/event/banner/:id',               to: 'events#banner_upload',                    as: :event_banner
  post   '/event/default_banner/:id',       to: 'events#banner_default',                   as: :event_default_banner
  patch  '/event/confirm',                  to: 'events#confirm_invitation',               as: :event_confirm_invitation
  patch  '/event/maybe',                    to: 'events#maybe_invitation',                 as: :event_maybe_invitation
  patch  '/event/reject',                   to: 'events#reject_invitation',                as: :event_reject_invitation
  patch  '/event/invite_customer/:id',      to: 'events#invite_customer',                  as: :event_invite_customer
  # Charity
  get    '/:username/charity/:id',           to: 'charity#view',                           as: :charity_view
  post   '/charity/update/:id',             to: 'charity#update',                          as: :charity_update
  post   '/charity/banner/:id',             to: 'charity#banner_upload',                   as: :charity_banner
  post   '/charity/default_banner/:id',     to: 'charity#banner_default',                  as: :charity_default_banner

  # Cash

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  customer_id :integer
#  max_gifts   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  basket_type :string           default("lifestyle")
#  description :text
#  banner      :string
#  share_count :integer          default(0)
#  privacy     :string           default("public")
#

class Basket < ApplicationRecord
  
  extend FriendlyId
  friendly_id             :name, use: :slugged

  BASKET_TYPES            = ["lifestyle", "charity", "cash", "event"].freeze
  PRIVACY_LEVELS          = ["public", "friends", "private"].freeze

  belongs_to              :customer, required: false
  has_many                :gifts, dependent: :destroy
  has_many                :comments, as: :commentable, dependent: :destroy
  has_one                 :event, dependent: :destroy
  has_one                 :charity, dependent: :destroy
  has_many                :likes, as: :likable, dependent: :destroy
  has_many                :activities, as: :actable, dependent: :destroy

  validates               :name, presence: true
  validates_uniqueness_of :name, scope: :customer_id
  validates_inclusion_of  :basket_type, in: BASKET_TYPES

  mount_uploader          :banner, BannerUploader

  before_destroy          :confirm_not_liked_products
  before_update           :confirm_not_liked_products
  before_update           :update_basket_slug
  after_create            :create_basket_slug

  def basket_slug_name
    self.try(:slug)
  end

  def create_basket_slug
    self.slug = "#{name}-#{id}".parameterize
    self.save!
  end

  def update_basket_slug
    self.slug = "#{name}-#{id}".parameterize
  end

  def self.basket_types
    BASKET_TYPES
  end

  def recent_gifts
    self.gifts.sort_by(&:updated_at).reverse[0..2]
  end

  def make_wishlist
    if( self.gifts.length > 20 )
      return false
    else
      self.max_gifts = 20
      self.save
    end
  end

  def visible_to?( customer )
    ( customer == self.customer ) || ( self.privacy == "public" ) || ( ( self.privacy == "friends" ) && ( customer.follows? self.customer ) )
  end

  def add_to_basket( variant, quantity = 1 )
    if( self.max_gifts.present? )
      return false if self.max_gifts <= self.gifts.length
    end
    unless( self.contains?(variant) )
      gift = Gift.create(
        basket_id: self.id,
        variant_id: variant.id,
        quantity_desired: quantity,
        quantity_received: 0
      )

      self.gifts << gift

      return true
    else
      return false
    end
  end

  def remove_from_basket(variant)
    if self.contains?(variant)
      gift = Gift.find_by_basket_id_and_variant_id(self.id, variant.id)

      gift.destroy

      return true

    else
      return false
    end
  end

  def nuke
    self.gifts.each do |gift|
      CartItem.where( gift_id: gift.id ).destroy_all
      gift.destroy
    end
    self.event.destroy if self.event.present?
    self.destroy
  end

  def contains?(variant)
    Gift.where( basket_id: self.id, variant_id: variant.id ).present?
  end

  def event?
    self.basket_type == "event"
  end

  def lifestyle?
    self.basket_type == "lifestyle"
  end

  def cash?
    self.basket_type == "cash"
  end

  def charity?
    self.basket_type == "charity"
  end

  def image_path
    if self.gifts.empty?
      '/images/events/createbasket_default.jpg'
    else
      self.gifts[0].variant.product_image.url
    end
  end

protected

  def confirm_not_liked_products
    if ( self.name_was == "Liked Products" ) && ( self.name != "Liked Products" )
      errors.add( :name, :cannot_alter, message: "Cannot alter Liked Products name" )
      p "#{self.class.to_s} Cannot alter Liked Products basket"
      return false
    else
      return true
    end
  end

end

app/controllers/api/v1/baskets_controller.rb
class Api::V1::BasketsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  before_action :authenticate_customer!

  def create
    @basket = current_customer.baskets.where(
                name: basket_params[:name]
              ).first_or_initialize
    if @basket.save
      render json: @basket.as_json
    else
      render json: {errors: @basket.errors.full_messages}, status: 500
    end
  end

  private

  def basket_params
    params.require(:basket).permit(
      :name
    )
  end

end

app/helpers/basket_helper.rb
module BasketHelper
end

app/views/basket/_modal_destroy_basket.html.erb
<div class="modal destroy_basket_modal fade" tabindex="-1" role="dialog" data-backdrop="static">

    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                <div class="modal_wrapper">
                    <div class="basket">
                        <div class="basket_inner">
                        <div class="basketPreview">
                                <% if @basket.lifestyle? %>
                                    <% if @basket.gifts.count >= 3 %>
                                        <div class="col-xs-8">
                                            <div class="basketprev1 basketPrevs" style="background-image:url(<%= @basket.gifts[-1].variant.product_image.medium.url %>);"></div>
                                        </div>

                                        <div class="col-xs-4 last">
                                            <div class="basketprev2 basketPrevs" style="background-image:url(<%= @basket.gifts[-2].variant.product_image.small.url %>);"></div>
                                            <div class="basketprev3 basketPrevs" style="background-image:url(<%= @basket.gifts[-3].variant.product_image.small.url %>);"></div>
                                        </div>
                                    <% elsif @basket.gifts.count == 0 %>
                                        <div class="col-xs-12">
                                            <div class="basketprev1 basketPrevs" style="background-image:url('/images/events/createbasket_default.jpg');"></div>
                                        </div>
                                    <% else %>
                                        <div class="col-xs-12">
                                            <div class="basketprev1 basketPrevs" style="background-image:url(<%= @basket.gifts[0].variant.product_image.medium.url %>);"></div>
                                        </div>
                                    <% end %>
                                <% else %>
                                    <div class="col-xs-12">
                                        <div class="basketprev1 basketPrevs" style="background-image:url(<%= @basket.banner.url %>);"></div>
                                    </div>
                                <% end %>
                            </div>
                        </div>
                    </div>
                    
                    <div class="text-center">
                        <h3><%=@basket.name%>
                            <% if @basket.lifestyle? %>
                            <%= ion_icon("record", aria_hidden: true, class: 'lifestyle_circle') %>
                            <% elsif @basket.event? %>
                            <%= ion_icon("record", aria_hidden: true, class: 'event_circle') %>
                            <% elsif @basket.charity? %>
                            <%= ion_icon("record", aria_hidden: true, class: 'charity_circle') %>
                            <% elsif @basket.cash? %>
                            <%= ion_icon("record", aria_hidden: true, class: 'cash_circle') %>
                            <% end %>
                        </h3>
                    </div>
                    <div class="text-center">
                        <p>Are You Sure you want to delete your Wish List?</p>
                        <p>This action cannot be undone.</p>
                    </div>
                    <div class="actions text-center">
                        <%= link_to 'Just Kidding!', '#', class: "btn btn-sm", data: { dismiss: "modal"} %>  
                        <%= link_to 'Yes, Delete Wish List', basket_destroy_path( @basket.id ), remote: true, method: 'delete',  class: "btn btn-sm"  %> 
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

app/views/basket/_popup_share_basket.html.erb
<div class="modal fade" id="share_modal" tabindex="-1" role="dialog" data-backdrop="static">
    <%= render partial: "shared/modals/modal_partials/close_btn" %>
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-body">
                    <%= link_to @link_url, alt: @verbiage do %>

                    <% if @share_type == 'Gift' || @share_type == 'Variant' %>
                        <div class="image_container">
                    <% else %>        
                        <div class="image_container banner" style="background-image: url('<%= @sharable.banner.url %>')">
                    <% end %>
                          <div class="mask">
                                <% if @share_type == 'Basket' %>
                                    <div class="gift">
                                        <p><%= @sharable.name %></p>
                                        <% if (@sharable.basket_type == 'lifestyle') ||  (@sharable.basket_type == 'charity') %>
                                            <p>
                                                <span>Wishes: <%= @sharable.gifts.count %></span>
                                                <% if @sharable.likes.count > 0 %>
                                                    <span>Likes: <%= @sharable.likes.count %></span>
                                                <% end %>
                                                <span>Shares: <%= @sharable.share_count %></span>
                                            </p>
                                        <% elsif @sharable.basket_type == 'event' %>
                                            <p>
                                                <span>Going: <%= @sharable.event.confirmed_count %></span>
                                                <span>Interested: <%= @sharable.event.maybe_count %></span>
                                                <span>Invited: <%= @sharable.event.pending_count %></span>
                                            </p>
                                        <% end %>    
                                    </div>
                                <% elsif @share_type == 'Customer' %>
                                    <div class="gift">
                                        <p><%= @sharable.name %></p>
                                        <p>
                                            <span>Wish Lists: <%= @sharable.baskets.count %></span>
                                            <span>Friends: <%= @sharable.connections.count %></span>
                                            <span>Total Wishes: <%= @sharable.gifts.count %></span>
                                        </p>
                                    </div>
                                <% elsif @share_type == 'Gift' %>
                                    <div class="gift">
                                        <p><%= @sharable.variant.trunc_name(35) %></p>
                                        <p>
                                            <span>Desired: <%= @sharable.quantity_desired %></span>
                                            <% if current_customer != @sharable.basket.customer %>
                                                <span>Received: <%= @sharable.quantity_received %></span>
                                            <% end %>
                                            <% if @sharable.likes.count > 0 %>
                                                <span>Likes: <%= @sharable.likes.count %></span>
                                            <% end %>
                                        </p>
                                    </div>
                                <% elsif  @share_type == 'Variant' %> 
                                    <div class="variant">
                                        <p><%= @sharable.trunc_name(60) %></p>
                                        <p><%= number_to_currency (@sharable.pretty_price) %><span><%= @sharable.merchant.name %></span></p>
                                    </div>
                                <% end %>
                          </div>
                            <% if @share_type == 'Gift' %>
                                <%= image_tag @sharable.variant.product_image.url, alt: '', class: 'img-responsive' %>
                            <% elsif  @share_type == 'Variant' %>  
                                <%= image_tag @sharable.product_image.url, alt: '', class: 'img-responsive' %>
                            <% end %>
                      </div>                  
                    <% end %>


                  <% if @share_type == 'Gift' || @share_type == 'Basket' %>
                  <%= link_to image_tag(@sharable.customer.avatar.profile.url, alt: 'avatar'), user_path(@sharable.customer.username), class: 'img-responsive avatar' %>
                  <p class="owner_name">
                      <%= @sharable.customer.name %>
                  </p>
                  <% elsif @share_type == 'Customer' %>
                      <%= link_to image_tag(@sharable.avatar.profile.url, alt: 'avatar'), user_path(@sharable.username), class: 'img-responsive avatar' %>
                      <p class="owner_name">
                      </p>
                  <% end %>
                <% if current_customer.present? %>
                    <div class="top">
                        <p>Share this <%= @verbiage %></p>
                    </div>  
                    <hr>   
                        <form action="#" class="form sharing_search">
                            <div class="form-group">
                                <input type="text" name="share_search" class="form-control input-md" placeholder="Search" />
                                <span class="glyphicon glyphicon-search"></span>
                            </div>
                        </form>
                        <ul class="list-unstyled friends 
                            <%= 'variant' if @share_type == 'Variant' %> 
                            <%= 'banner' if @share_type == 'Customer' || @share_type == 'Basket' %> 
                            <%= 'safari_mobile' if (browser.safari? && browser.mobile?) %>
                            <%= @share_type %>
                        ">
                        <% current_customer.connections.each do |connection| %>
                             <li class="list-group-item friend" data-connection="<%= connection.id %>">
                                 <%= image_tag connection.avatar.profile_square.url, alt: 'avatar', class: 'img-responsive' %>
                                 <span><%= connection.name %></span>
                                 <%= ion_icon("ios-checkmark", aria_hidden: true, class: 'pull-right hidden') %>
                             </li>
                        <% end %>
                    </ul>
                <% else %>
                    <% if @share_type == 'Gift' || @share_type == 'Variant' %>
                        <div class="mask_preview">
                    <% else %>        
                        <div class="mask_preview banner">
                    <% end %>
                        <div>
                            <span>From here, you can share items with your connections. Please</span>
                            <%= link_to 'Login', '#login_modal', data: {toggle: 'modal'}, rel:'nofollow' %>
                            <span>or</span>
                            <%= link_to 'Sign Up', new_customer_registration_path, class: "sign_up" %>
                            <span>to share.</span>
                        </div>
                    </div>
                <% end %>
                <% if current_customer.present? %>
                    <div class="share_social">
                        <!-- copy link -->
                        <%= link_to '#', class: "copy copy_basket", rel:'nofollow', data: {clipboard_action: "copy", clipboard_text: @share_url} do %>
                            <%= ion_icon("link") %>
                        <% end %>                      
                        <!-- social link -->

                        <%= link_to ion_icon("social-facebook"), "https://www.facebook.com/sharer/sharer.php?u=#{@share_url}", title: 'facebook share', target: '_blank', rel:'nofollow' %>
                        <%= link_to ion_icon("social-pinterest"), "https://pinterest.com/pin/create/button/?url=#{@share_url}&media=#{@image_url}&description=#{@name}", title: 'pinterest share', target: '_blank', rel:'nofollow' %>
                        <%= link_to ion_icon("social-twitter"), "https://twitter.com/intent/tweet?text=#{@name}&amp;url=#{@share_url}", title: 'twitter share', target: '_blank', rel:'nofollow' %>

                        <button class="btn share_basket disabled">Share <%= ion_icon("ios-paperplane") %></button>
                    </div>
                <% end %>
            </div>
        </div>
    </div>
</div>

app/views/basket/index.html.erb
BASKET, YO!
<br>
<%= link_to "Back to profile", user_index_path %>
<br>
<br>
<p>
<% if @baskets.blank? %>
  Oh no! You have no Baskets yet! <%= link_to "Make one?", "/#" %>
<% else %>
  You have <%= @baskets.count %> Baskets<hr>
  <% @baskets.each do |basket| %>
    <div id="basket_<%= basket.id %>_block" >
    <b><%= basket.name %></b><br>
    <p>
      <% if basket.gifts.blank? %>
        Oh no! You have no Gifts yet! <%= link_to "Add some!", products_index_path %>
      <% else %>
        <% basket.gifts.each do |gift| %>
          <p id="gift_<%= gift.id %>_block">
            <%= gift.variant.name %> <%= "**INVALID**" if gift.variant.invalid? %>
            <%= link_to "Remove From Basket", "#", id: "remove_gift_#{gift.id}", class: "basket_removal" %>
          </p>
        <% end %>
      <% end %>
      </p>
    </p>
    <p>
    <%= link_to "Delete this Basket", "#", id: "delete_basket_#{basket.id}", class: "delete_basket" %>
    </p>
    <hr>
    </div>
  <% end %>
<% end %>

<div id="create_basket_block">
  <%= link_to "Create New Basket", "#", id: "create_basket" %>
</div>

<div id="basket_name_block" style="display: none">
  Name of New Basket: <%= text_field :basket_name, :create_box %><br/>
  <%= submit_tag "Create New Basket", id: "create_basket_button" %>
</div>

<script>
$('#create_basket').click(function(event){

  // Hide create new basket link
  $('#create_basket_block').hide();
  // Reveal textfield for adding name w/ confirm button 
  $('#basket_name_block').show();
  event.preventDefault();

});

$('#create_basket_button').click(function(event){
  var basket_name = $('#basket_name_create_box').val();

  var formData = {
    'name' : basket_name
  }

  // ajax basket_name to controller
  $.ajax({
    type     : 'POST',
    url      : 'basket/create',
    data     : formData,
    dataType : 'json',
    encode   : true
  })

  $('#create_basket_block').show();
  $('#basket_name_block').hide();

  event.preventDefault();
});

$('.basket_removal').click(function(event){
  // event.target.id
  var ray = event.target.id.split("_");

  var formData = {
    'gift_id'   : ray[2]
  };

  $.ajax({
    type     : 'DELETE',
    url      : 'gift/destroy',
    data     : formData,
    dataType : 'json',
    encode   : true
  })

  $('#gift_' + ray[2] + '_block').hide();
  event.preventDefault();
});


$('.delete_basket').click(function(event){
  var ray = event.target.id.split("_");

  var formData = {
    'basket_id'  : ray[2]
  };

  $.ajax({
    type     : 'DELETE',
    url      : 'basket/destroy',
    data     : formData,
    dataType : 'json',
    encode   : true
  })

  $('#basket_' + ray[2] + '_block').hide();
  event.preventDefault();
});
</script>

app/views/basket/modal_builder.js.erb
//geocomplete 
$(".event_address").geocomplete().bind("geocode:result", function(event, result){
	console.log(result);
});

// // replace basket images back to original 
$(".create_modal").on('hide.bs.modal', function () {
	$('input#variant_id, input#quantity').remove();
})

//hidden variant id for creating basket with item 
$('<input>').attr({
    type: 'hidden',
    id: 'variant_id',
    name: 'basket[variant_id]',
    value: '<%= @variant.id %>'
}).appendTo('#lifestyle #new_basket, #event #new_basket, #charity #new_basket, #cash #new_basket');

//hidden quantity for creating basket with item 
$('<input>').attr({
    type: 'hidden',
    id: 'quantity',
    name: 'basket[quantity]',
    value: $(".qty").val()
}).appendTo('#lifestyle #new_basket, #event #new_basket, #charity #new_basket, #cash #new_basket');

//open create modal
$('.create_modal').modal(open);

app/views/basket/paginate_basket.js.erb
<% @gifts.reverse.each do |gift| %>
	html = $('<%= escape_javascript(render partial: "shared/tiles/product_tile", locals: {product: gift, tile: "basket"}) %>')
    $("#gifts .products").append(html);
<% end %>

connections_autocomplete("search_wishes", <%=raw @gifts_arr %>);