config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }, skip: [ :sessions, :registration, :password ]
  mount ActionCable.server => '/cable'

  scope '/api' do
    scope '/v1' do
      scope '/baskets' do
        get   '/'        => 'api_baskets#index'
        get   '/create'  => 'api_baskets#create'
      end
      scope '/merchants' do
        get  '/'         => 'api_merchants#check'
      end
      scope '/products' do
        get  '/'         => 'api_products#show'
      end
      scope  '/gifts' do
        post '/add-tags' => 'api_gifts#add_tags'
      end
      scope  '/errors' do
        post '/'         => 'api_errors#submit'
      end

    end
  end

  #======== Cart feature ==========
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:none] do
        collection do
          get 'items'
          get 'items_count'
        end
      end
      resources :api_reports, only: [:create] do
        collection do
          post 'confirm'
        end
      end
      resources :cart_items, only: [:index, :create, :update, :destroy]
      resources :payment_methods, only: [:new, :create]
      resources :checkouts, only: [:create] do
        collection do
          post 'select_shipping_option'
          post 'select_shipping_address'
          post 'select_payment_method'
          get  'review'
        end
      end
      resources :addresses
      resource :gift_urls, only: [:create] do
        get :show, on: :member
        get :baskets, on: :member
        post :html, on: :member
      end
      resources :baskets, only: [:create]
    end
  end

  namespace :ajax_partials do
    resources :shipping_addresses_form, only: [:index, :new]
    resources :payment_methods_form, only: [:index, :new]
    resources :checkouts, only: [] do
      collection do
        get 'sidebar'
        get 'empty_cart'
        get 'cart_tab'
        get 'review_shipping_option'
        get 'review_payment_method'
        get 'review_shipping_address'
      end
    end
    resource :giftboxes, only: [:none] do
      collection do
        get 'giftboxes_modal'
      end
    end
  end

  #admins
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  authenticated :admin do
    namespace :admin do
      resources :app_settings, only: [:index, :edit, :update]
      resources :purchasers do
        member do
          post 'reset_password'
        end
      end
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      resource :ga_reporting, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :brand_manager, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :deals, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :merchant_categories, only: [:none] do
        collection do
          get 'home'
          get 'categories'
          get 'category'
          get 'new'
          post 'add'
          post 'edit'
          delete 'delete'
        end
      end
      resource :feedback, only: [:none] do
        collection do
          get 'home'
          get 'complaints'
          get 'purchases'
          get 'mailinglist'
        end
      end
      root 'dashboards#home', as: :root
    end
  end

  #error status route
  match    ':status',                       to: 'errors#show',                             constraints: {status: /\d{3}/}, via: :all

  get      'admin/brands/view/:id',         to: 'admin/brand_managers#view',               as: :view_admin_brand_manager
  patch    'admin/brands/edit/:id',         to: 'admin/brand_managers#edit',               as: :edit_admin_brand_manager

  get      'admin/deals/view/:id',          to: 'admin/deals#view',                        as: :view_admin_deals
  patch    'admin/deals/edit/:id',          to: 'admin/deals#edit',                        as: :edit_admin_deals
  get      'admin/deals/new',               to: 'admin/deals#new',                         as: :new_admin_deals
  post     'admin/deals/create',            to: 'admin/deals#create',                      as: :create_admin_deals

  resources :guests, only: [:update]

  #=====================

  patch '/admin/ga_reporting/resolve',      to: 'admin#ga_reports_resolve',                as: :resolve_ga_reports
  patch '/admin/complaints/resolve',        to: 'admin#complaints_resolve',                as: :complaints_reports

  #admins
  devise_for :purchaser, controllers: {
    sessions: "purchasers/sessions"
  }
  authenticated :purchaser do
    namespace :purchasers do
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      root 'shipping_orders#index', as: :root
    end
  end


  get :token, controller: 'application'

  as :customer do
    # Custom Devise routes for Registration
    get    'register',                      to: 'customers/registrations#new',             as: :new_customer_registration
    post   'register',                      to: 'customers/registrations#create',          as: :customer_registration
    get    'cancel',                        to: 'devise/registrations#cancel',             as: :cancel_customer_registration
    get    'edit',                          to: 'devise/registrations#edit',               as: :edit_customer_registration
    patch  'update',                        to: 'devise/registration#update'
    put    'update',                        to: 'devise/registrations#update'
    delete 'destroy',                       to: 'devise/registrations#destroy'

    # Custom Devise routes for Session
    get    'login',                         to: 'custom_sessions#new',                     as: :new_customer_session
    post   'login',                         to: 'custom_sessions#create',                  as: :customer_session
    delete 'logout',                        to: 'custom_sessions#destroy',                 as: :destroy_customer_session

    # Custom Devise routes for Password
    get    'password/',                     to: 'customers/passwords#new',                    as: :new_customer_password
    post   'password/',                     to: 'customers/passwords#create',                 as: :create_customer_password
    get    'password/edit',                 to: 'customers/passwords#edit',                   as: :edit_customer_password
    post   'password/update',               to: 'customers/passwords#update',                 as: :update_customer_password
    # patch  'password',                      to: 'devise/passwords#update'
    # put    'password',                      to: 'devise/passwords#update'
  end

  resources :media_contents, only: [:create]

  resources :conversations do
    resources :messages do
      collection do
        post :read
      end
    end
  end
  get '/messages/not_read'

  # Baskets
  get    '/:username/registry/:id',         to: 'basket#view',                             as: :basket_view
  post   '/basket/add/:id',                 to: 'basket#add',                              as: :basket_add
  delete '/basket/remove/:id',              to: 'basket#remove',                           as: :basket_remove
  post   '/basket/create',                  to: 'basket#create',                           as: :basket_create
  delete '/basket/destroy/:id',             to: 'basket#destroy',                          as: :basket_destroy

  post   '/basket/update/:id',              to: 'basket#update',                           as: :basket_update
  patch  '/basket/share/:id',               to: 'basket#share',                            as: :basket_share
  patch  '/basket/clone/:id',               to: 'basket#clone',                            as: :basket_clone
  post   '/basket/banner/:id',              to: 'basket#banner_upload',                    as: :basket_banner
  post   '/basket/default_banner/:id',      to: 'basket#banner_default',                   as: :lifestyle_default_banner

  # Event
  get    '/:username/event/:id',            to: 'events#view',                             as: :event_view
  post   '/event/remove/:id',               to: 'events#remove',                           as: :event_remove
  post   '/event/update/:id',               to: 'events#update',                           as: :event_update
  post   '/event/banner/:id',               to: 'events#banner_upload',                    as: :event_banner
  post   '/event/default_banner/:id',       to: 'events#banner_default',                   as: :event_default_banner
  patch  '/event/confirm',                  to: 'events#confirm_invitation',               as: :event_confirm_invitation
  patch  '/event/maybe',                    to: 'events#maybe_invitation',                 as: :event_maybe_invitation
  patch  '/event/reject',                   to: 'events#reject_invitation',                as: :event_reject_invitation
  patch  '/event/invite_customer/:id',      to: 'events#invite_customer',                  as: :event_invite_customer
  # Charity
  get    '/:username/charity/:id',           to: 'charity#view',                           as: :charity_view
  post   '/charity/update/:id',             to: 'charity#update',                          as: :charity_update
  post   '/charity/banner/:id',             to: 'charity#banner_upload',                   as: :charity_banner
  post   '/charity/default_banner/:id',     to: 'charity#banner_default',                  as: :charity_default_banner

  # Cash

app/models/merchant_category.rb
class MerchantCategory < ApplicationRecord

	extend FriendlyId
	friendly_id             :name, use: :slugged

	mount_uploader :screenshot, Category_Uploader
	before_update           :update_category_slug
  	after_create            :create_category_slug

	def category_merchants
		Merchant.where(id: self.merchants )
	end

	def create_category_slug
		self.slug = name.parameterize
		self.save!
	end

	def update_category_slug
		self.slug = name.parameterize
	end

end

app/controllers/admin/merchant_categories_controller.rb
class Admin::MerchantCategoriesController < AdminController
  layout 'admin'
  before_action :all_merchants

  def categories
  	@categories = MerchantCategory.all.order(name: 'ASC')
  end

  def category
  	@category = MerchantCategory.find(params[:id])
  	checked_merchants = @category.category_merchants  	
  	unchecked_merchants = @all_merchants - checked_merchants
  	@checked_merchants = checked_merchants.order(name: 'ASC')
  	@unchecked_merchants = unchecked_merchants.group_by{|c| c.name.first.downcase}.sort_by{|k, v| k}
  end

  def new
  	@all_merchants = @all_merchants.group_by{|c| c.name.first.downcase}.sort_by{|k, v| k}
  end

  def add
  	merchant_list = params[:merchant_category][:merchants]
  	category = MerchantCategory.new 
  	category.name = params[:merchant_category][:name].downcase
  	category.merchants = merchant_list
  	category.screenshot = params[:merchant_category][:screenshot]

  	merchant_list.each do |id|
  		merchant = Merchant.find(id)
  		merchant.category_list.add( params[:merchant_category][:name] )
  		merchant.save
  	end

    if category.valid?
       category.save!
       flash[:success] = "You Created a New Category"
    else
       flash[:error] = "Somthing went wrong please try again"
    end

    respond_to do |format|
      format.html { redirect_to request.referer }
    end

  end

  def edit
  	new_merchants = params[:merchant_category][:merchants].present? ? params[:merchant_category][:merchants] : []
  	old_merchants = params[:merchant_category][:old_merchants].present? ? params[:merchant_category][:old_merchants] : []
  	merchant_list = new_merchants + old_merchants
  	category = MerchantCategory.find(params[:id])
  	category.name = params[:merchant_category][:name].downcase if params[:merchant_category][:name].present?
  	category.merchants = merchant_list if !merchant_list.empty?
  	category.screenshot = params[:merchant_category][:screenshot] if params[:merchant_category][:screenshot].present?

  	if !merchant_list.empty?
	  	@all_merchants.each do |merchant|
	  		if merchant.category_list.include?( params[:merchant_category][:name].downcase )
	  			merchant.category_list.delete( params[:merchant_category][:name] )
	  		end
	  		merchant.save
	  	end
	  	category.category_merchants.each do |merchant|
	  		merchant.category_list.add( params[:merchant_category][:name].downcase )	
	  		merchant.save
	  	end
  	end

  	if category.valid?
       category.save!
       flash[:success] = "Category Successfully Edited"
    else
       flash[:error] = "Somthing went wrong please try again"
    end

    respond_to do |format|
      format.html { redirect_to request.referer }
    end
  	
  end


  def delete
  	category = MerchantCategory.find(params[:id])

  	@all_merchants.each do |merchant|
  		if merchant.category_list.include?( category.name.downcase )
  			merchant.category_list.delete( category.name.downcase )
  			merchant.save
  		end
  	end

  	if category.valid?
       category.destroy
       flash[:success] = "Category Successfully Deleted"
    else
       flash[:error] = "Somthing went wrong please try again"
    end

  	respond_to do |format|
      format.html { redirect_to request.referer }
    end

  end

  private

  def all_merchants
  	@all_merchants = Merchant.all.order(name: 'ASC')
  end

end

app/views/admin/merchant_categories/categories.html.erb
<%= link_to '< back', home_admin_merchant_categories_path %>
<h2 class="reports_text">Categories</h2>
<h3 class="reports_text"> All Categories (<%= @categories.count %>) </h3>

<div class="ga_reports_container">
	<% if !@categories.empty? %>

	    <% @categories.each do |category| %>
	    <table>
	        <thead>
	            <th>Category Name</th>
	            <th>Category ID</th>
	            <th>Merchants</th>
	            <th>Screenshot</th>
	            <th>Actions</th>
	        </thead>
	        <tr>
	            <td><%= category.name %></td>
	            <td><%= category.id %></td>
	            <td>
	            <% category.category_merchants.each do |merchant| %>
	            <span class="label label-default"><%= merchant.name %></span>
	            <% end %>
	            </td>
	            <td>
	            	<%= image_tag category.screenshot.small.url, class: 'img-responsive' %>
	            </td>
	            <td>
	            	<%= link_to 'edit', category_admin_merchant_categories_path(id:category.id), class: 'btn btn-default' %>  
	            	<%= link_to 'delete', delete_admin_merchant_categories_path(id:category.id), remote: true, method: 'delete', class: 'btn btn-danger ' %>
	            </td>
	        </tr>

	    </table>
	    <br>
	    <% end %>
    <% end %>
</div>


<div></div>

app/views/admin/merchant_categories/category.html.erb
<%= link_to '< back', categories_admin_merchant_categories_path %>

<h2 class="reports_text">Edit <%=@category.name%></h2>
<div id="add_category">
    <%= form_for @category, url: edit_admin_merchant_categories_path(id: @category.id), remote: true, method: 'post', html: { multipart: true } do |f| %>
        
        <div class="form-group has-feedback letter_section">
        <%= f.text_field :name, class: "form-control input-md category-name", placeholder: "Add Category Name", required: true %>
        </div>

        <div class="form-group has-feedback letter_section">
            <% @checked_merchants.each do |merchant|%>
                <div class="letter_container col-xs-3">
                    <%= f.check_box :old_merchants, { multiple: true, checked: true }, merchant.id, nil %>
                    <%= f.label merchant.name %>
                </div>
            <% end %>
        </div>
        <div class="form-group has-feedback letter_section">
            <% @unchecked_merchants.each do |char, merchant|%>
                <div class="letter_container col-xs-3">
                    <p class="letter"><%= char.capitalize %></p>
                    <div>
                        <% merchant.each do |m| %>
                            <div class="field form-group checkbox checkbox-warning">
                                <%= f.check_box :merchants, { multiple: true }, m.id, nil %>
                                <%= label_tag m.name %>
                            </div>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="form-upload">
            <%= image_tag @category.screenshot.small.url, class: 'img-responsive' %>
            <div class="form-group has-feedback">
                <%= f.file_field :screenshot, class: 'btn btn-default' %>
            </div>

            <div class="form-group">
                <%= f.submit class: 'btn btn-success'%>
            </div>
        </div>
    <% end %>
</div>

app/views/admin/merchant_categories/home.html.erb
<h2 class="reports_text">Manage Categories</h2>
<div id="feedback_container">

  <ul class="nav flex-column">
    <li class="nav-item">
      <%= link_to 'View Categories', categories_admin_merchant_categories_path %>
    </li>
    <li class="nav-item">
      <%= link_to 'Add New Category', admin_merchant_categories_path %>
    </li>
  </ul>
</div>

app/views/admin/merchant_categories/new.html.erb
 <%= link_to '< back', home_admin_merchant_categories_path %>
<h2 class="reports_text">Add New Category</h2>
<div id="add_category">
    <%= form_for MerchantCategory.new, url: add_admin_merchant_categories_path, remote: true, html: { multipart: true } do |f| %>
        <div class="form-group has-feedback">
            <%= f.text_field :name, class: "form-control input-md category-name", placeholder: "Add Category Name", required: true %>
            <div class="help-block with-errors"></div>
        </div>

        <div class="form-group has-feedback letter_section">
            <% @all_merchants.each do |char, merchant|%>
                <div class="letter_container col-xs-3">
                    <p class="letter"><%= char.capitalize %></p>
                    <div>
                        <% merchant.each do |m| %>
                            <div class="field form-group checkbox checkbox-warning">
                                <%= f.check_box :merchants, { multiple: true }, m.id, nil %>
                                <%= label_tag m.name %>
                            </div>
                        <% end %>
                    </div>
                </div>
            <% end %>
        </div>
        <div class="form-upload">
            <div class="form-group has-feedback">
                <%= f.file_field :screenshot, required: true, class: 'btn btn-default' %>
            </div>

            <div class="form-group has-feedback">
                <%= f.submit class: 'btn btn-success'%>
            </div>
        </div>
    <% end %>
</div>