config/routes.rb
Rails.application.routes.draw do
  devise_for :customers, controllers: { omniauth_callbacks: "customers/omniauth_callbacks" }, skip: [ :sessions, :registration, :password ]
  mount ActionCable.server => '/cable'

  scope '/api' do
    scope '/v1' do
      scope '/baskets' do
        get   '/'        => 'api_baskets#index'
        get   '/create'  => 'api_baskets#create'
      end
      scope '/merchants' do
        get  '/'         => 'api_merchants#check'
      end
      scope '/products' do
        get  '/'         => 'api_products#show'
      end
      scope  '/gifts' do
        post '/add-tags' => 'api_gifts#add_tags'
      end
      scope  '/errors' do
        post '/'         => 'api_errors#submit'
      end

    end
  end

  #======== Cart feature ==========
  namespace :api do
    namespace :v1 do
      resources :carts, only: [:none] do
        collection do
          get 'items'
          get 'items_count'
        end
      end
      resources :api_reports, only: [:create] do
        collection do
          post 'confirm'
        end
      end
      resources :cart_items, only: [:index, :create, :update, :destroy]
      resources :payment_methods, only: [:new, :create]
      resources :checkouts, only: [:create] do
        collection do
          post 'select_shipping_option'
          post 'select_shipping_address'
          post 'select_payment_method'
          get  'review'
        end
      end
      resources :addresses
      resource :gift_urls, only: [:create] do
        get :show, on: :member
        get :baskets, on: :member
        post :html, on: :member
      end
      resources :baskets, only: [:create]
    end
  end

  namespace :ajax_partials do
    resources :shipping_addresses_form, only: [:index, :new]
    resources :payment_methods_form, only: [:index, :new]
    resources :checkouts, only: [] do
      collection do
        get 'sidebar'
        get 'empty_cart'
        get 'cart_tab'
        get 'review_shipping_option'
        get 'review_payment_method'
        get 'review_shipping_address'
      end
    end
    resource :giftboxes, only: [:none] do
      collection do
        get 'giftboxes_modal'
      end
    end
  end

  #admins
  devise_for :admins, controllers: {
    sessions: "admins/sessions"
  }
  authenticated :admin do
    namespace :admin do
      resources :app_settings, only: [:index, :edit, :update]
      resources :purchasers do
        member do
          post 'reset_password'
        end
      end
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      resource :ga_reporting, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :brand_manager, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :deals, only: [:none] do
        collection do
          get 'home'
        end
      end
      resource :merchant_categories, only: [:none] do
        collection do
          get 'home'
          get 'categories'
          get 'category'
          get 'new'
          post 'add'
          post 'edit'
          delete 'delete'
        end
      end
      resource :feedback, only: [:none] do
        collection do
          get 'home'
          get 'complaints'
          get 'purchases'
          get 'mailinglist'
        end
      end
      root 'dashboards#home', as: :root
    end
  end

  #error status route
  match    ':status',                       to: 'errors#show',                             constraints: {status: /\d{3}/}, via: :all

  get      'admin/brands/view/:id',         to: 'admin/brand_managers#view',               as: :view_admin_brand_manager
  patch    'admin/brands/edit/:id',         to: 'admin/brand_managers#edit',               as: :edit_admin_brand_manager

  get      'admin/deals/view/:id',          to: 'admin/deals#view',                        as: :view_admin_deals
  patch    'admin/deals/edit/:id',          to: 'admin/deals#edit',                        as: :edit_admin_deals
  get      'admin/deals/new',               to: 'admin/deals#new',                         as: :new_admin_deals
  post     'admin/deals/create',            to: 'admin/deals#create',                      as: :create_admin_deals

  resources :guests, only: [:update]

  #=====================

  patch '/admin/ga_reporting/resolve',      to: 'admin#ga_reports_resolve',                as: :resolve_ga_reports
  patch '/admin/complaints/resolve',        to: 'admin#complaints_resolve',                as: :complaints_reports

  #admins
  devise_for :purchaser, controllers: {
    sessions: "purchasers/sessions"
  }
  authenticated :purchaser do
    namespace :purchasers do
      resources :shipping_orders, only: [:index, :show, :update] do
        member do
          get 'mark_as_complete'
        end
      end
      resources :merchant_carts, only: [:show, :update] do
        member do
          get 'start'
        end
      end
      root 'shipping_orders#index', as: :root
    end
  end


  get :token, controller: 'application'

  as :customer do
    # Custom Devise routes for Registration
    get    'register',                      to: 'customers/registrations#new',             as: :new_customer_registration
    post   'register',                      to: 'customers/registrations#create',          as: :customer_registration
    get    'cancel',                        to: 'devise/registrations#cancel',             as: :cancel_customer_registration
    get    'edit',                          to: 'devise/registrations#edit',               as: :edit_customer_registration
    patch  'update',                        to: 'devise/registration#update'
    put    'update',                        to: 'devise/registrations#update'
    delete 'destroy',                       to: 'devise/registrations#destroy'

    # Custom Devise routes for Session
    get    'login',                         to: 'custom_sessions#new',                     as: :new_customer_session
    post   'login',                         to: 'custom_sessions#create',                  as: :customer_session
    delete 'logout',                        to: 'custom_sessions#destroy',                 as: :destroy_customer_session

    # Custom Devise routes for Password
    get    'password/',                     to: 'customers/passwords#new',                    as: :new_customer_password
    post   'password/',                     to: 'customers/passwords#create',                 as: :create_customer_password
    get    'password/edit',                 to: 'customers/passwords#edit',                   as: :edit_customer_password
    post   'password/update',               to: 'customers/passwords#update',                 as: :update_customer_password
    # patch  'password',                      to: 'devise/passwords#update'
    # put    'password',                      to: 'devise/passwords#update'
  end

  resources :media_contents, only: [:create]

  resources :conversations do
    resources :messages do
      collection do
        post :read
      end
    end
  end
  get '/messages/not_read'

  # Baskets
  get    '/:username/registry/:id',         to: 'basket#view',                             as: :basket_view
  post   '/basket/add/:id',                 to: 'basket#add',                              as: :basket_add
  delete '/basket/remove/:id',              to: 'basket#remove',                           as: :basket_remove
  post   '/basket/create',                  to: 'basket#create',                           as: :basket_create
  delete '/basket/destroy/:id',             to: 'basket#destroy',                          as: :basket_destroy

  post   '/basket/update/:id',              to: 'basket#update',                           as: :basket_update
  patch  '/basket/share/:id',               to: 'basket#share',                            as: :basket_share
  patch  '/basket/clone/:id',               to: 'basket#clone',                            as: :basket_clone
  post   '/basket/banner/:id',              to: 'basket#banner_upload',                    as: :basket_banner
  post   '/basket/default_banner/:id',      to: 'basket#banner_default',                   as: :lifestyle_default_banner

  # Event
  get    '/:username/event/:id',            to: 'events#view',                             as: :event_view
  post   '/event/remove/:id',               to: 'events#remove',                           as: :event_remove
  post   '/event/update/:id',               to: 'events#update',                           as: :event_update
  post   '/event/banner/:id',               to: 'events#banner_upload',                    as: :event_banner
  post   '/event/default_banner/:id',       to: 'events#banner_default',                   as: :event_default_banner
  patch  '/event/confirm',                  to: 'events#confirm_invitation',               as: :event_confirm_invitation
  patch  '/event/maybe',                    to: 'events#maybe_invitation',                 as: :event_maybe_invitation
  patch  '/event/reject',                   to: 'events#reject_invitation',                as: :event_reject_invitation
  patch  '/event/invite_customer/:id',      to: 'events#invite_customer',                  as: :event_invite_customer
  # Charity
  get    '/:username/charity/:id',           to: 'charity#view',                           as: :charity_view
  post   '/charity/update/:id',             to: 'charity#update',                          as: :charity_update
  post   '/charity/banner/:id',             to: 'charity#banner_upload',                   as: :charity_banner
  post   '/charity/default_banner/:id',     to: 'charity#banner_default',                  as: :charity_default_banner

  # Cash

app/models/basket.rb
# == Schema Information
#
# Table name: baskets
#
#  id          :integer          not null, primary key
#  name        :string           not null
#  customer_id :integer
#  max_gifts   :integer
#  created_at  :datetime
#  updated_at  :datetime
#  basket_type :string           default("lifestyle")
#  description :text
#  banner      :string
#  share_count :integer          default(0)
#  privacy     :string           default("public")
#

class Basket < ApplicationRecord
  
  extend FriendlyId
  friendly_id             :name, use: :slugged

  BASKET_TYPES            = ["lifestyle", "charity", "cash", "event"].freeze
  PRIVACY_LEVELS          = ["public", "friends", "private"].freeze

  belongs_to              :customer, required: false
  has_many                :gifts, dependent: :destroy
  has_many                :comments, as: :commentable, dependent: :destroy
  has_one                 :event, dependent: :destroy
  has_one                 :charity, dependent: :destroy
  has_many                :likes, as: :likable, dependent: :destroy
  has_many                :activities, as: :actable, dependent: :destroy

  validates               :name, presence: true
  validates_uniqueness_of :name, scope: :customer_id
  validates_inclusion_of  :basket_type, in: BASKET_TYPES

  mount_uploader          :banner, BannerUploader

  before_destroy          :confirm_not_liked_products
  before_update           :confirm_not_liked_products
  before_update           :update_basket_slug
  after_create            :create_basket_slug

  def basket_slug_name
    self.try(:slug)
  end

  def create_basket_slug
    self.slug = "#{name}-#{id}".parameterize
    self.save!
  end

  def update_basket_slug
    self.slug = "#{name}-#{id}".parameterize
  end

  def self.basket_types
    BASKET_TYPES
  end

  def recent_gifts
    self.gifts.sort_by(&:updated_at).reverse[0..2]
  end

  def make_wishlist
    if( self.gifts.length > 20 )
      return false
    else
      self.max_gifts = 20
      self.save
    end
  end

  def visible_to?( customer )
    ( customer == self.customer ) || ( self.privacy == "public" ) || ( ( self.privacy == "friends" ) && ( customer.follows? self.customer ) )
  end

  def add_to_basket( variant, quantity = 1 )
    if( self.max_gifts.present? )
      return false if self.max_gifts <= self.gifts.length
    end
    unless( self.contains?(variant) )
      gift = Gift.create(
        basket_id: self.id,
        variant_id: variant.id,
        quantity_desired: quantity,
        quantity_received: 0
      )

      self.gifts << gift

      return true
    else
      return false
    end
  end

  def remove_from_basket(variant)
    if self.contains?(variant)
      gift = Gift.find_by_basket_id_and_variant_id(self.id, variant.id)

      gift.destroy

      return true

    else
      return false
    end
  end

  def nuke
    self.gifts.each do |gift|
      CartItem.where( gift_id: gift.id ).destroy_all
      gift.destroy
    end
    self.event.destroy if self.event.present?
    self.destroy
  end

  def contains?(variant)
    Gift.where( basket_id: self.id, variant_id: variant.id ).present?
  end

  def event?
    self.basket_type == "event"
  end

  def lifestyle?
    self.basket_type == "lifestyle"
  end

  def cash?
    self.basket_type == "cash"
  end

  def charity?
    self.basket_type == "charity"
  end

  def image_path
    if self.gifts.empty?
      '/images/events/createbasket_default.jpg'
    else
      self.gifts[0].variant.product_image.url
    end
  end

protected

  def confirm_not_liked_products
    if ( self.name_was == "Liked Products" ) && ( self.name != "Liked Products" )
      errors.add( :name, :cannot_alter, message: "Cannot alter Liked Products name" )
      p "#{self.class.to_s} Cannot alter Liked Products basket"
      return false
    else
      return true
    end
  end

end

app/controllers/api/v1/baskets_controller.rb
class Api::V1::BasketsController < ApplicationController
  protect_from_forgery with: :null_session
  skip_before_action :verify_authenticity_token
  before_action :authenticate_customer!

  def create
    @basket = current_customer.baskets.where(
                name: basket_params[:name]
              ).first_or_initialize
    if @basket.save
      render json: @basket.as_json
    else
      render json: {errors: @basket.errors.full_messages}, status: 500
    end
  end

  private

  def basket_params
    params.require(:basket).permit(
      :name
    )
  end

end

app/helpers/basket_helper.rb
module BasketHelper
end

app/views/shared/baskets/_basket_edit.html.erb
<div class="container-fluid tab_full_width edit_basket_container" style="display: none;">
    <div class="col-xs-12 col-sm-12 col-md-6 col-md-push-3">
        <% if basket_type == 'lifestyle' %>
            <%= form_for @basket, url: basket_update_path(@basket.id), method: :post do |f| %>

            <h2 class="text-center">Edit Wish List</h2>

            <div class="col-xs-12">
                <div class="form-group">
                    <label for="name">Wish List Name</label>
                    <% if @basket.name == "Liked Products" %>
                      <div><%= @basket.name %></div>
                    <% else %>
                      <%= f.text_field :name, class: "form-control input-md", maxlength: "30", placeholder: "basket name", data: { error: "basket name missing" }, required: true %>
                    <% end %>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <label for="description">Wish List Description</label>
                    <%= f.text_area :description, rows: "5", class: "form-control input-md", placeholder: "Edit basket description", data: { error: "basket description missing" } %>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="col-xs-12">
                <label for="privacy" style="text-align:center">Wish List Privacy</label>
                <div class="form-group basket_privacy">
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "public" %>
                        <%= label_tag :age_public, "Public" %>
                        <%= ion_icon("android-globe", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "friends" %>
                        <%= label_tag :age_friends, "Friends Only" %>
                        <%= ion_icon("ios-people", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "private" %>
                        <%= label_tag :age_private, "Private" %>
                        <%= ion_icon("ios-locked", aria_hidden: true) %>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 col-sm-12 col-md-12 top-10 text-right">
                <a href="#" class="edit_basket_btn">Cancel</a>
                <%= f.submit "Save Changes", class: "save_basket_edit" %>
            </div>

            <% end %>
        <% elsif basket_type == 'event' %>
            <%= form_for @basket.event, url: event_update_path(@basket.event.id), method: :post do |f| %>

            <h2 class="text-center">Edit Wish List</h2>

            <div class="col-xs-12">
                <div class="form-group">
                    <label for="name">Event Name</label>
                    <%= f.text_field :name, class: "form-control input-md", maxlength: "30", placeholder: "Title", data: { error: "event name missing" }, required: true %>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <label for="event_occurs_at">Event Date</label>
                    <div class='input-group date-time-picker'>
                        <%= f.text_field :occurs_at, value: event_date_format(@basket.event.occurs_at), class: "form-control input-md date-time-picker", placeholder: "MM/DD/YYYY", data: { error: "event date missing" }, required: true %>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-calendar"></span>
                        </span>
                        <div class="help-block with-errors"></div>
                    </div>
                </div>
            </div>

            <div class="col-xs-12">
                <div class="form-group">
                    <label for="name">Event Location</label>
                    <%= f.text_field :location, class: "form-control input-md", placeholder: "Location", data: { error: "event location missing" }, required: true %>

                    <div class="help-block with-errors"></div>
                </div>
            </div>


            <div class="col-xs-12">
                <div class="form-group">
                    <label for="description">Event Description</label>
                    <%= f.text_area :description, rows: "5", class: "form-control input-md", placeholder: "Edit basket description", data: { error: "event description missing" } %>
                    <div class="help-block with-errors"></div>
                </div>
            </div>

            <div class="col-xs-12">
                <label for="privacy" style="text-align:center">Event Privacy</label>
                <div class="form-group basket_privacy">
                    <div class="radio radio-warning radio-inline">
                        <%= radio_button_tag :privacy, "public", ( @basket.privacy == "public" ) %> 
                        <%= label_tag :age_public, "Public" %>
                        <%= ion_icon("android-globe", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= radio_button_tag :privacy, "friends", ( @basket.privacy == "friends" ) %> 
                        <%= label_tag :age_friends, "Friends Only" %>
                        <%= ion_icon("ios-people", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= radio_button_tag :privacy, "private", ( @basket.privacy == "private" ) %> 
                        <%= label_tag :age_private, "Private" %>
                        <%= ion_icon("ios-locked", aria_hidden: true) %>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 text-right">
                <a href="#" class="edit_basket_btn"> Cancel </a>
                <%= f.submit "Save Changes", class: "save_basket_edit top-20" %>
            </div>

            <% end %>
        <% elsif basket_type == 'charity' %>
            <%= form_for @basket, url: charity_update_path(@basket.id), method: :post do |f| %>

            <h2 class="text-center">Edit Wish List</h2>

            <div class="col-xs-12">
              <div class="form-group edit_basket">
                <label for="name">Charity Name</label>
                <%= f.text_field :name, class: "form-control input-md", maxlength: "30", placeholder: "Title", data: { error: "charity name missing" }, required: true %>
                <div class="help-block with-errors"></div>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group edit_basket">
                <label for="date">Charity Description</label>
                <%= f.text_field :description, class: "form-control input-md", placeholder: "Edit basket description", data: { error: "charity description missing" } %>
                <div class="help-block with-errors"></div>
              </div>
            </div>

            <div class="col-xs-12">
              <div class="form-group edit_basket">
                <label for="name">Charity Url</label>
                <%= text_field_tag :url, @basket.charity.url, class: "form-control input-md", placeholder: "http://giftibly.com" %>
                <div class="help-block with-errors"></div>
              </div>
            </div>

            <div class="col-xs-12">
                <label for="privacy" style="text-align:center">Charity Privacy</label>
                <div class="form-group basket_privacy">
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "public" %>
                        <%= label_tag :age_public, "Public" %>
                        <%= ion_icon("android-globe", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "friends" %>
                        <%= label_tag :age_friends, "Friends Only" %>
                        <%= ion_icon("ios-people", aria_hidden: true) %>
                    </div>
                    <div class="radio radio-warning radio-inline">
                        <%= f.radio_button :privacy, "private" %>
                        <%= label_tag :age_private, "Private" %>
                        <%= ion_icon("ios-locked", aria_hidden: true) %>
                    </div>
                </div>
            </div>

            <div class="col-xs-12 text-right">
              <a href="#" class="edit_basket_btn">Cancel</a>
              <%= f.submit "Save Changes", class: "save_basket_edit top-20" %>
            </div>

            <% end %>
        <% end %>
    </div>
</div>